// 1 = Read, 2 = Create, 3 = Update, 4 = Delete
const permission = {
  superAdmin: {
    branch: [1, 2, 3, 4],
    department: [1, 2, 3, 4],
    employee: [1, 2, 3, 4],
    attandence: [1, 2, 3, 4],
    holiday: [1, 2, 3, 4],
    leave: [1, 2, 3, 4],
    salary: [1, 2, 3, 4],
    advance: [1, 2, 3, 4],
    voucher: [1, 2, 3, 4],
    ledger: [1, 2, 3, 4],
    ledger_entry: [1, 2, 3, 4],
    weekly_off_ledger: [1, 2, 3, 4],
    plot_inventory: [1, 2, 3, 4],
    plot_booking: [1, 2, 3, 4],
    plot_collection: [1, 2, 3, 4],
    plot_sponsor: [1, 2, 3, 4],
    plot_customer: [1, 2, 3, 4],
    plot_payout: [1, 2, 3, 4],
    plot_reports: [1, 2, 3, 4],
    investment: [1, 2, 3, 4],
    audit_log: [1, 4],
    notification: [1, 2, 3, 4],
  },
  Admin: {
    branch: [1, 2, 3, 4],
    department: [1, 2, 3, 4],
    employee: [1, 2, 3, 4],
    attandence: [1, 2, 3, 4],
    holiday: [1, 2, 3, 4],
    leave: [1, 2, 3, 4],
    salary: [1, 2, 3, 4],
    advance: [1, 2, 3, 4],
    voucher: [1, 2, 3, 4],
    ledger: [1, 2, 3, 4],
    ledger_entry: [1, 2, 3, 4],
    weekly_off_ledger: [1, 2, 3, 4],
    plot_inventory: [1, 2, 3, 4],
    plot_booking: [1, 2, 3, 4],
    plot_collection: [1, 2, 3, 4],
    plot_sponsor: [1, 2, 3, 4],
    plot_customer: [1, 2, 3, 4],
    plot_payout: [1, 2, 3, 4],
    plot_reports: [1, 2, 3, 4],
    investment: [1, 2, 3, 4],
    audit_log: [1],
    notification: [1, 2, 3, 4],
  },
  manager: {
    branch: [1],
    department: [1, 2, 3],
    employee: [1, 2, 3],
    attandence: [1, 2, 3],
    holiday: [1, 2],
    leave: [1, 2, 3],
    salary: [1],
    advance: [1, 2, 3],
    voucher: [1, 2, 3, 4],
    ledger: [1, 2, 3, 4],
    ledger_entry: [1, 2, 3, 4],
    weekly_off_ledger: [1, 2, 3],
    plot_inventory: [1],
    plot_booking: [1, 2, 3],
    plot_collection: [1, 2, 3],
    plot_sponsor: [1],
    plot_customer: [1, 2, 3],
    plot_payout: [1],
    plot_reports: [1],
    investment: [1, 2, 3],
    audit_log: [1],
    notification: [1, 2],
  },
  employee: {
    attandence: [1],
    holiday: [1],
    leave: [1, 2],
    salary: [1],
    advance: [1],
    ledger: [1],
    notification: [1],
  },
  demo: {
    branch: [1],
    department: [1],
    employee: [1],
    attandence: [1],
    holiday: [1],
    leave: [1],
    salary: [1],
    advance: [1],
    voucher: [1],
    ledger: [1],
    ledger_entry: [1],
    weekly_off_ledger: [1],
    plot_inventory: [1],
    plot_booking: [1],
    plot_collection: [1],
    plot_sponsor: [1],
    plot_customer: [1],
    plot_payout: [1],
    plot_reports: [1],
    investment: [1],
    audit_log: [1],
    notification: [1],
  },
};

module.exports = permission;

